apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hk-transportation-mcp

resources:
  - deployment.yaml
  - cronjob.yaml
  - ingress.yaml
  - config.yaml
  - hpa.yaml
  - redis.yaml
